import pytest

from dialects import MySQLDialect, PostgresDialect
from schema import CanonicalType, ColumnSpec, ForeignKeySpec, IndexSpec, TableSpec


@pytest.fixture
def postgres():
    return PostgresDialect()


def column(name, type_, **kwargs):
    return ColumnSpec(name=name, type=type_, **kwargs)


class TestMySQLCanonicalTypes:
    """MySQL's width suffixes carry meaning the DATA_TYPE alone loses."""

    def test_tinyint_1_is_boolean(self):
        # Rails and MySQL both spell boolean as tinyint(1).
        assert MySQLDialect._canonical_type("tinyint", "tinyint(1)") is CanonicalType.BOOLEAN

    def test_wider_tinyint_is_a_number(self):
        assert MySQLDialect._canonical_type("tinyint", "tinyint(4)") is CanonicalType.SMALLINT

    @pytest.mark.parametrize(
        "data_type, column_type, expected",
        [
            ("int", "int(11)", CanonicalType.INTEGER),
            ("bigint", "bigint(20)", CanonicalType.BIGINT),
            ("varchar", "varchar(255)", CanonicalType.VARCHAR),
            ("decimal", "decimal(10,2)", CanonicalType.NUMERIC),
            ("datetime", "datetime", CanonicalType.TIMESTAMP),
            ("longtext", "longtext", CanonicalType.TEXT),
            ("blob", "blob", CanonicalType.BINARY),
            ("enum", "enum('a','b')", CanonicalType.TEXT),
        ],
    )
    def test_mapping(self, data_type, column_type, expected):
        assert MySQLDialect._canonical_type(data_type, column_type) is expected

    def test_unknown_type_raises_rather_than_guessing(self):
        with pytest.raises(ValueError, match="no canonical mapping"):
            MySQLDialect._canonical_type("geometry", "geometry")


class TestPostgresDDL:
    def test_identity_column_allows_explicit_values(self, postgres):
        # BY DEFAULT, not ALWAYS: the migration inserts existing key values.
        spec = TableSpec(
            name="users",
            columns=[column("id", CanonicalType.INTEGER, nullable=False, is_identity=True)],
            primary_key=("id",),
        )
        ddl = postgres.render_create_table(spec)
        assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
        assert "GENERATED ALWAYS" not in ddl

    def test_reserved_words_and_case_are_quoted(self, postgres):
        # An unquoted "default" is a syntax error and status_of_NCR would fold
        # to lowercase, silently not matching the source column.
        spec = TableSpec(
            name="reports",
            columns=[
                column("default", CanonicalType.VARCHAR, length=255),
                column("status_of_NCR", CanonicalType.VARCHAR, length=255),
            ],
        )
        ddl = postgres.render_create_table(spec)
        assert '"default" varchar(255)' in ddl
        assert '"status_of_NCR" varchar(255)' in ddl

    def test_numeric_keeps_precision_and_scale(self, postgres):
        spec = TableSpec(
            name="t",
            columns=[column("amount", CanonicalType.NUMERIC, precision=10, scale=2)],
        )
        assert "numeric(10,2)" in postgres.render_create_table(spec)

    def test_numeric_without_scale_defaults_to_zero(self, postgres):
        spec = TableSpec(
            name="t",
            columns=[column("qty", CanonicalType.NUMERIC, precision=10, scale=None)],
        )
        assert "numeric(10,0)" in postgres.render_create_table(spec)

    def test_varchar_without_length_becomes_text(self, postgres):
        spec = TableSpec(name="t", columns=[column("body", CanonicalType.VARCHAR)])
        assert " text" in postgres.render_create_table(spec)

    def test_not_null_and_default_render(self, postgres):
        spec = TableSpec(
            name="t",
            columns=[column("n", CanonicalType.INTEGER, nullable=False, default="0")],
        )
        ddl = postgres.render_create_table(spec)
        assert "DEFAULT 0" in ddl and "NOT NULL" in ddl

    def test_junk_numeric_default_is_dropped(self, postgres):
        # MySQL tolerates defaults on numeric columns that Postgres rejects.
        spec = TableSpec(
            name="t",
            columns=[column("n", CanonicalType.INTEGER, default="No")],
        )
        assert "DEFAULT" not in postgres.render_create_table(spec)

    def test_string_default_is_escaped(self, postgres):
        spec = TableSpec(
            name="t",
            columns=[column("s", CanonicalType.VARCHAR, length=10, default="it's")],
        )
        assert "DEFAULT 'it''s'" in postgres.render_create_table(spec)

    def test_primary_key_constraint(self, postgres):
        spec = TableSpec(
            name="t",
            columns=[column("a", CanonicalType.INTEGER), column("b", CanonicalType.INTEGER)],
            primary_key=("a", "b"),
        )
        assert 'PRIMARY KEY ("a", "b")' in postgres.render_create_table(spec)

    def test_table_without_primary_key_omits_constraint(self, postgres):
        spec = TableSpec(name="t", columns=[column("a", CanonicalType.INTEGER)])
        assert "PRIMARY KEY" not in postgres.render_create_table(spec)


class TestPostgresIndexes:
    def test_index_names_are_namespaced_to_avoid_collision(self, postgres):
        # MySQL index names are per-table; Postgres index names are global.
        spec = TableSpec(
            name="orders",
            indexes=[IndexSpec(name="index_on_name", columns=("name",))],
        )
        assert '"orders_index_on_name"' in postgres.render_indexes(spec)[0]

    def test_already_prefixed_name_is_left_alone(self, postgres):
        spec = TableSpec(
            name="users",
            indexes=[IndexSpec(name="users_email_idx", columns=("email",))],
        )
        assert '"users_email_idx"' in postgres.render_indexes(spec)[0]

    def test_unique_index_renders_unique(self, postgres):
        spec = TableSpec(
            name="users",
            indexes=[IndexSpec(name="u", columns=("email",), unique=True)],
        )
        assert "CREATE UNIQUE INDEX" in postgres.render_indexes(spec)[0]

    def test_no_indexes_yields_no_statements(self, postgres):
        assert postgres.render_indexes(TableSpec(name="t")) == []


class TestPostgresForeignKeys:
    def test_renders_reference(self, postgres):
        spec = TableSpec(
            name="attachments",
            foreign_keys=[
                ForeignKeySpec(
                    name="fk_blob",
                    columns=("blob_id",),
                    referenced_table="blobs",
                    referenced_columns=("id",),
                )
            ],
        )
        statement = postgres.render_foreign_keys(spec)[0]
        assert 'ALTER TABLE "attachments"' in statement
        assert 'REFERENCES "blobs" ("id")' in statement


class TestBooleanCoercion:
    """MySQL hands back 0/1; a Postgres boolean column will not take those."""

    def test_integers_become_booleans(self, postgres):
        rows = [{"flag": 1}, {"flag": 0}]
        result = postgres.coerce_rows(rows, {"flag": "boolean"})
        assert result == [{"flag": True}, {"flag": False}]

    def test_nulls_are_preserved(self, postgres):
        result = postgres.coerce_rows([{"flag": None}], {"flag": "boolean"})
        assert result == [{"flag": None}]

    def test_non_boolean_columns_are_untouched(self, postgres):
        rows = [{"n": 1}]
        assert postgres.coerce_rows(rows, {"n": "integer"}) == [{"n": 1}]

    def test_mysql_does_not_coerce(self):
        rows = [{"flag": 1}]
        assert MySQLDialect().coerce_rows(rows, {"flag": "boolean"}) == [{"flag": 1}]


class TestNulByteStripping:
    """MySQL stores NUL bytes in text; Postgres rejects the whole batch."""

    @pytest.mark.parametrize(
        "native_type",
        ["text", "character varying(255)", "character(10)", "varchar(50)"],
    )
    def test_nul_is_stripped_from_character_columns(self, postgres, native_type):
        rows = [{"note": "before\x00after"}]
        result = postgres.coerce_rows(rows, {"note": native_type})
        assert result == [{"note": "beforeafter"}]

    def test_multiple_nuls_all_go(self, postgres):
        rows = [{"note": "\x00a\x00b\x00"}]
        assert postgres.coerce_rows(rows, {"note": "text"}) == [{"note": "ab"}]

    def test_clean_values_are_untouched(self, postgres):
        rows = [{"note": "nothing wrong here"}]
        assert postgres.coerce_rows(rows, {"note": "text"})[0]["note"] == (
            "nothing wrong here"
        )

    def test_none_is_preserved(self, postgres):
        assert postgres.coerce_rows([{"note": None}], {"note": "text"}) == [
            {"note": None}
        ]

    def test_stripping_is_reported_not_silent(self, postgres, capsys):
        postgres.coerce_rows([{"note": "a\x00b"}], {"note": "text"})
        assert "stripped NUL bytes" in capsys.readouterr().out

    def test_boolean_and_nul_coercion_compose(self, postgres):
        rows = [{"flag": 1, "note": "a\x00b"}]
        result = postgres.coerce_rows(rows, {"flag": "boolean", "note": "text"})
        assert result == [{"flag": True, "note": "ab"}]


class TestUnsupportedCapabilities:
    def test_mysql_cannot_render_ddl_yet(self):
        # MySQL works as a translation source but not as a target; the error
        # should say which side is missing rather than an AttributeError.
        with pytest.raises(NotImplementedError, match="cannot render DDL"):
            MySQLDialect().render_create_table(TableSpec(name="t"))

    def test_postgres_cannot_describe_tables_yet(self):
        with pytest.raises(NotImplementedError, match="cannot describe tables"):
            PostgresDialect().describe_table(None, "t")
